import {stableId} from './rng.js';
import {knows,learn} from './epistemics.js';
import {appendEvent} from './ledger.js';
import {consumeObjectQuantity,MATERIAL_PROPERTIES,objectMass} from './materials.js';
import {structureOccupancyAt,terrainAt} from './terrain.js';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function registerDesign(world,citizen,spec,at=world.clock.worldMinute){for(const concept of spec.concepts||[])if(!knows(citizen,concept))throw new Error(`unknown_concept:${concept}`);if(!spec.materials||!Object.keys(spec.materials).length)throw new Error('design_materials_required');const d={id:spec.id||stableId('design',citizen.id,world.designs.length),creatorId:citizen.id,concepts:[...(spec.concepts||[])],materials:{...spec.materials},workMinutes:Math.max(1,Number(spec.workMinutes)||1),functionConcept:spec.functionConcept||null,createdWorldMinute:at,origin:'explicit-material-design'};world.designs.push(d);appendEvent(world,'DESIGN_REGISTERED',citizen.id,{designId:d.id,conceptIds:d.concepts},[],at);return d;}
export function registerEmpiricalDesign(world,citizen,{concepts=[],inputObjectIds=[],workMinutes=120,form='structure'}={},at=world.clock.worldMinute){for(const concept of concepts)if(!knows(citizen,concept))throw new Error(`unknown_concept:${concept}`);const objects=inputObjectIds.map(id=>world.objects.find(o=>o.id===id&&o.holderId===citizen.id&&o.quantity>0));if(objects.some(x=>!x)||!objects.length)throw new Error('design_inputs_unavailable');const materials={};for(const o of objects)materials[o.material]=(materials[o.material]||0)+o.quantity;const d={id:stableId('design',citizen.id,world.designs.length,at),creatorId:citizen.id,concepts:[...concepts],materials,workMinutes:Math.max(15,Number(workMinutes)||120),functionConcept:null,createdWorldMinute:at,origin:'empirical',form:String(form||'structure').slice(0,32)};world.designs.push(d);appendEvent(world,'DESIGN_REGISTERED',citizen.id,{designId:d.id,conceptIds:d.concepts,origin:d.origin,form:d.form},[],at);return d;}
function foundationMultiplier(kind){return kind==='wetland'?1.65:kind==='rocky'?1.25:kind==='forest'?1.15:kind==='dry_grass'?1.03:1;}
function validateSite(world,site){const x=Number(site?.x),y=Number(site?.y);if(!Number.isFinite(x)||!Number.isFinite(y)||x<1||x>99||y<1||y>99)throw new Error('construction_site_invalid');if(structureOccupancyAt(world,x,y))throw new Error('construction_site_occupied');if((world.projects||[]).some(p=>p.status==='construction'&&Math.hypot(x-p.site.x,y-p.site.y)<2.2))throw new Error('construction_site_project_conflict');const terrain=terrainAt(world,x,y);if(terrain.kind==='river')throw new Error('construction_site_unstable_water');return {x,y,terrain};}
export function beginConstruction(world,citizen,designId,site,objectIds,at=world.clock.worldMinute){const d=world.designs.find(x=>x.id===designId);if(!d)throw new Error('design_not_found');const checked=validateSite(world,site),objects=objectIds.map(id=>world.objects.find(o=>o.id===id));if(objects.some(x=>!x))throw new Error('material_object_not_found');for(const [material,needed] of Object.entries(d.materials)){const available=objects.filter(o=>o.material===material&&o.holderId===citizen.id&&!o.reservedProjectId).reduce((s,o)=>s+o.quantity,0);if(available<needed)throw new Error(`insufficient_material:${material}`);}const foundationFactor=foundationMultiplier(checked.terrain.kind),p={id:stableId('project',designId,citizen.id,world.projects.length),designId,initiatorId:citizen.id,site:{x:checked.x,y:checked.y},terrainKind:checked.terrain.kind,foundationFactor,materialObjectIds:[...objectIds],workRequiredMinutes:Math.ceil(d.workMinutes*foundationFactor),workDoneMinutes:0,status:'construction',createdWorldMinute:at};world.projects.push(p);for(const o of objects)o.reservedProjectId=p.id;appendEvent(world,'CONSTRUCTION_STARTED',citizen.id,{projectId:p.id,designId,site:p.site,terrainKind:p.terrainKind,foundationFactor:p.foundationFactor,workRequiredMinutes:p.workRequiredMinutes},[],at);return p;}
export function beginEmpiricalConstruction(world,citizen,spec,at=world.clock.worldMinute){const design=registerEmpiricalDesign(world,citizen,{concepts:spec.concepts,inputObjectIds:spec.inputObjectIds,workMinutes:spec.workMinutes,form:spec.form},at);return beginConstruction(world,citizen,design.id,spec.site,spec.inputObjectIds,at);}
function protectionFromMaterials(incorporated){let mass=0,thermal=0,water=0;for(const [material,quantity] of Object.entries(incorporated)){const q=Math.max(0,Number(quantity)||0),p=MATERIAL_PROPERTIES[material]||MATERIAL_PROPERTIES.composite;mass+=q;thermal+=q*Number(p.thermalResistance||.25);water+=q*Number(p.waterResistance||.35);}if(mass<=0)return{thermal:.2,precipitation:.25};return{thermal:clamp(thermal/mass,.08,.95),precipitation:clamp(water/mass,.08,.98)};}
export function applyConstructionWork(world,citizen,projectId,minutes,at=world.clock.worldMinute){const p=world.projects.find(x=>x.id===projectId);if(!p||p.status!=='construction')throw new Error('project_not_active');if(!citizen.alive)throw new Error('citizen_dead');p.workDoneMinutes=Math.min(p.workRequiredMinutes,p.workDoneMinutes+Math.max(0,Number(minutes)||0));appendEvent(world,'CONSTRUCTION_WORK',citizen.id,{projectId,minutes,workDoneMinutes:p.workDoneMinutes},[],at);if(p.workDoneMinutes<p.workRequiredMinutes)return p;const d=world.designs.find(x=>x.id===p.designId);const incorporated={};let incorporatedMassKg=0;for(const [material,needed0] of Object.entries(d.materials)){let needed=needed0;for(const id of p.materialObjectIds){const o=world.objects.find(x=>x.id===id);if(!o||o.material!==material||needed<=0)continue;const q=Math.min(o.quantity,needed);incorporated[material]=(incorporated[material]||0)+q;incorporatedMassKg+=q*o.massPerUnitKg;consumeObjectQuantity(world,o.id,q,p.id,at);needed-=q;}if(needed>0)throw new Error(`construction_material_missing:${material}`);}for(const id of p.materialObjectIds){const o=world.objects.find(x=>x.id===id);if(o)delete o.reservedProjectId;}p.status='completed';const protection=protectionFromMaterials(incorporated),b={id:stableId('building',p.id),kind:'structure',designId:d.id,position:{...p.site},footprintRadius:1.55,condition:1,massKg:incorporatedMassKg,materials:incorporated,protection,createdWorldMinute:at,occupants:[],accessAgreements:[],provenance:{projectId:p.id,designId:d.id,initiatorId:p.initiatorId}};world.buildings.push(b);appendEvent(world,'BUILDING_COMPLETED',citizen.id,{projectId:p.id,buildingId:b.id,designId:d.id,massKg:incorporatedMassKg,protection},[],at);return p;}
function observableProperties(material,object=null){const p=object?.properties||MATERIAL_PROPERTIES[material]||{};return Object.fromEntries(Object.entries(p).filter(([,v])=>typeof v==='number'||typeof v==='boolean'));}
export function runExperiment(world,citizen,spec,at=world.clock.worldMinute){for(const c of spec.inputConcepts||[])if(!knows(citizen,c))throw new Error(`unknown_concept:${c}`);const targets=[];for(const id of spec.targetIds||[]){const o=world.objects.find(x=>x.id===id&&x.holderId===citizen.id);const d=world.resourceDeposits.find(x=>x.id===id&&citizen.knownEntityIds.includes(id));if(o)targets.push({id,material:o.material,massKg:objectMass(o),object:o});else if(d)targets.push({id,material:d.type,massKg:null});else throw new Error(`experiment_target_unavailable:${id}`);}const observations=[];const discovered=[];for(const t of targets){for(const [property,value] of Object.entries(observableProperties(t.material,t.object))){const concept=stableId('kprop',t.id,property);const evidence={entityId:t.id,property,value,method:String(spec.method||'direct-test').slice(0,32)};learn(citizen,concept,{kind:'experiment',evidence},.85,at);observations.push({conceptId:concept,evidence});discovered.push(concept);}}const e={id:stableId('exp',citizen.id,world.experiments.length,at),actorId:citizen.id,inputConcepts:[...(spec.inputConcepts||[])],targetIds:targets.map(x=>x.id),observations,discoveredConceptIds:discovered,result:observations.length?'observations-recorded':'inconclusive',worldMinute:at};world.experiments.push(e);appendEvent(world,'EXPERIMENT_COMPLETED',citizen.id,{experimentId:e.id,targetIds:e.targetIds,discoveredConceptIds:discovered,result:e.result},[],at);return e;}
