import {validateProposalKnowledge,knows} from './epistemics.js';
import {ACTION_TYPES,SAFE_REFLEX_ACTIONS} from './constants.js';
import {startAction,activeAction,interruptAction} from './actions.js';
import {stableId,hash32} from './rng.js';
import {resourceConceptId,structureConceptId,sensoryEvidence} from './perception.js';
import {objectMass} from './materials.js';
import {adoptBelief} from './beliefs.js';

function heldObjects(world,citizen){return world.objects.filter(o=>o.holderId===citizen.id&&o.quantity>0);}
export function buildCognitiveContext(world,citizen,at=world.clock.worldMinute){const nearbyCitizens=world.citizens.filter(c=>c.id!==citizen.id&&c.alive&&Math.hypot(c.position.x-citizen.position.x,c.position.y-citizen.position.y)<=10).filter(c=>citizen.knownEntityIds.includes(c.id)).map(c=>({id:c.id,selfName:c.selfName}));const knownResources=world.resourceDeposits.filter(d=>citizen.knownEntityIds.includes(d.id)&&knows(citizen,resourceConceptId(d))).map(d=>({entityId:d.id,conceptId:resourceConceptId(d),position:d.position,evidence:sensoryEvidence(d)}));const possessions=heldObjects(world,citizen).map(o=>({id:o.id,kind:o.kind,massKg:objectMass(o),quantity:o.quantity,provenanceType:o.provenance?.type||null}));const projects=world.projects.filter(p=>p.initiatorId===citizen.id&&p.status==='construction').map(p=>({id:p.id,position:p.site,progress:p.workRequiredMinutes?Math.round(p.workDoneMinutes/p.workRequiredMinutes*100):0}));const knownStructures=[...(world.buildings||[]),...(world.objects||[]).filter(o=>o.kind==='temporary_shelter'&&o.quantity>0)].filter(x=>citizen.knownEntityIds.includes(x.id)&&knows(citizen,structureConceptId(x))).map(x=>({entityId:x.id,conceptId:structureConceptId(x),position:x.position,physicalEvidence:{boundedCover:true,thermalProtection:Number(x.properties?.thermalProtection??x.protection?.thermal??.5)}}));return {worldMinute:at,self:{id:citizen.id,body:{hydration:citizen.body.hydration,calories:citizen.body.calories,sleepPressure:citizen.body.sleepPressure,health:citizen.body.health},position:citizen.position,psychology:citizen.psychology,activeGoal:citizen.activeGoal?{concepts:citizen.activeGoal.concepts||[],actionTypes:citizen.activeGoal.actionTypes||[]}:null},knowledge:citizen.knowledge.filter(k=>k.active!==false).map(k=>({id:k.concept,confidence:k.confidence,evidence:k.provenance.map(p=>p.evidence).filter(Boolean).slice(-3)})),memories:citizen.memories.slice(-18).map(m=>({kind:m.kind,content:m.content,confidence:m.confidence})),knownEntities:nearbyCitizens,knownResources,knownStructures,possessions,projects,relationships:Object.fromEntries(Object.entries(citizen.relationships).filter(([id])=>citizen.knownEntityIds.includes(id))),beliefs:(citizen.beliefs||[]).map(b=>({id:b.id,stanceCode:b.stanceCode,conceptIds:b.conceptIds,confidence:b.confidence})).slice(-24),externalDirection:world.privateHumanIntents[citizen.id]?.intent||null};}

function validateBeliefUpdates(citizen,proposal){for(const b of proposal?.beliefUpdates||[]){for(const concept of b.conceptIds||[])if(!knows(citizen,concept))return {ok:false,reason:`unknown_concept:${concept}`};}return {ok:true};}
function validatePayload(world,citizen,a){const held=new Set(heldObjects(world,citizen).map(o=>o.id));const p=a.payload||{};if(['BUILD','ASSEMBLE','CUT','DIG','HEAT','COOL','MIX'].includes(a.type)){for(const id of p.inputObjectIds||p.transformation?.inputObjectIds||[])if(!held.has(id))return {ok:false,reason:`object_not_held:${id}`};}if(a.type==='TRANSFER'&&p.objectId&&!held.has(p.objectId))return {ok:false,reason:`object_not_held:${p.objectId}`};if(['TEACH','COMMUNICATE','PROMISE','CLAIM'].includes(a.type)){for(const c of [p.concept,...(p.conceptIds||[]),p.purposeConcept,p.ruleConcept].filter(Boolean))if(!knows(citizen,c))return {ok:false,reason:`unknown_concept:${c}`};}if(a.type==='COMMUNICATE'&&p.beliefId&&!(citizen.beliefs||[]).some(b=>b.id===p.beliefId))return {ok:false,reason:`belief_not_held:${p.beliefId}`};return {ok:true};}
export function validateCognitiveProposal(world,citizen,proposal){if(!proposal||typeof proposal!=='object')return {ok:false,reason:'proposal_invalid'};const knowledge=validateProposalKnowledge(world,citizen,proposal);if(!knowledge.ok)return knowledge;const beliefs=validateBeliefUpdates(citizen,proposal);if(!beliefs.ok)return beliefs;if(!Array.isArray(proposal.actions))return {ok:false,reason:'actions_required'};for(const a of proposal.actions){if(!ACTION_TYPES.has(a.type))return {ok:false,reason:`action_invalid:${a.type}`};if(a.targetId&&a.targetId!==citizen.id&&!citizen.knownEntityIds.includes(a.targetId)&&!world.projects.some(p=>p.id===a.targetId&&p.initiatorId===citizen.id))return {ok:false,reason:`unknown_target:${a.targetId}`};const pv=validatePayload(world,citizen,a);if(!pv.ok)return pv;}return {ok:true};}
export function applyAcceptedPlan(world,citizen,proposal,at=world.clock.worldMinute){const validation=validateCognitiveProposal(world,citizen,proposal);if(!validation.ok)throw new Error(validation.reason);for(const b of proposal.beliefUpdates||[])adoptBelief(world,citizen,b,{kind:'reflection'},at);const current=activeAction(world,citizen);if(current&&['OBSERVE','REST'].includes(current.type))interruptAction(world,citizen,'cognitive_plan',at);else if(current)throw new Error('citizen_busy');const plan={id:stableId('plan',citizen.id,citizen.plans.length,at),createdWorldMinute:at,concepts:[...(proposal.concepts||[])],actions:proposal.actions,status:'active',cursor:0,source:proposal.source||'cognition'};if(!['reflex','local'].includes(plan.source))citizen.activeGoal={concepts:plan.concepts,actionTypes:plan.actions.map(a=>a.type),source:plan.source,createdWorldMinute:at};citizen.plans.push(plan);citizen.cognition.pending=false;if(plan.actions.length){const a=plan.actions[0];startAction(world,citizen,{...a,planId:plan.id,durationMinutes:a.durationMinutes||10},at);}else plan.status='completed';return plan;}
export function continuePlan(world,citizen,completedAction,at){if(!completedAction.planId)return false;const plan=citizen.plans.find(p=>p.id===completedAction.planId);if(!plan||plan.status!=='active')return false;plan.cursor++;if(plan.cursor>=plan.actions.length){plan.status='completed';if(citizen.activeGoal)citizen.activeGoal.lastPlanCompletedWorldMinute=at;citizen.cognition.pending=true;return false;}const a=plan.actions[plan.cursor];startAction(world,citizen,{...a,planId:plan.id,durationMinutes:a.durationMinutes||10},at);return true;}
export function survivalFallback(world,citizen){if(!citizen.alive||citizen.currentActionId)return null;const b=citizen.body,ambient=Number(world.environment?.temperatureC??18);if(ambient<5||ambient>36){const structures=[...(world.buildings||[]),...(world.objects||[]).filter(o=>o.kind==='temporary_shelter'&&o.quantity>0)].filter(x=>citizen.knownEntityIds.includes(x.id)).sort((a,b)=>dist(citizen.position,a.position)-dist(citizen.position,b.position));const s=structures[0];if(s&&dist(citizen.position,s.position)>1)return {source:'reflex',concepts:[],actions:[{type:'MOVE',durationMinutes:Math.max(2,Math.ceil(dist(citizen.position,s.position)*2)),targetId:s.id,targetPosition:s.position,purpose:'survival',concepts:[]},{type:'REST',durationMinutes:30,purpose:'survival'}]};}const infant=b.ageMinutes<2*525600;if(infant&&(b.hydration<55||b.calories<55||b.sleepPressure>75)){const caregiver=Object.keys(citizen.relationships||{})[0]||citizen.knownEntityIds.find(id=>id!==citizen.id);return caregiver?{source:'reflex',concepts:[],actions:[{type:'COMMUNICATE',durationMinutes:2,targetId:caregiver,purpose:'survival',payload:{primitiveSignal:'need'}},{type:'REST',durationMinutes:8,purpose:'survival'}]}:{source:'reflex',concepts:[],actions:[{type:'REST',durationMinutes:8,purpose:'survival'}]};}if(b.sleepPressure>85)return {source:'reflex',concepts:[],actions:[{type:'SLEEP',durationMinutes:240,purpose:'survival'}]};if(b.hydration<35)return nearestKnownResourcePlan(world,citizen,'water','DRINK');if(b.calories<30)return nearestKnownResourcePlan(world,citizen,'food','EAT');return null;}
function nearestKnownResourcePlan(world,citizen,type,terminal){const ds=world.resourceDeposits.filter(d=>d.type===type&&knows(citizen,resourceConceptId(d))).sort((a,b)=>dist(citizen.position,a.position)-dist(citizen.position,b.position));const d=ds[0];if(!d)return {source:'reflex',concepts:[],actions:[{type:'OBSERVE',durationMinutes:10,purpose:'orientation'}]};const distance=dist(citizen.position,d.position),concept=resourceConceptId(d);return {source:'reflex',concepts:[concept],actions:distance>1?[{type:'MOVE',durationMinutes:Math.max(2,Math.ceil(distance*2)),targetPosition:d.position,targetId:d.id,purpose:'biological_need',concepts:[concept]},{type:terminal,durationMinutes:5,targetId:d.id,purpose:'biological_need',concepts:[concept]}]:[{type:terminal,durationMinutes:5,targetId:d.id,purpose:'biological_need',concepts:[concept]}]};}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y);}

export function localDeliberation(world,citizen,at=world.clock.worldMinute){
  if(!citizen.alive||citizen.currentActionId)return null;
  const goal=citizen.activeGoal||null,desired=new Set(goal?.actionTypes||[]),concepts=(goal?.concepts||[]).filter(c=>knows(citizen,c));
  if(desired.has('BUILD')){const project=world.projects.find(p=>p.initiatorId===citizen.id&&p.status==='construction');if(project)return {source:'local',concepts,actions:[{type:'BUILD',durationMinutes:Math.min(120,Math.max(15,project.workRequiredMinutes-project.workDoneMinutes)),targetId:project.id,purpose:'construct',concepts,payload:{projectId:project.id,workMinutes:120}}]};}
  if(desired.has('GATHER')){const d=world.resourceDeposits.find(x=>citizen.knownEntityIds.includes(x.id)&&concepts.includes(resourceConceptId(x))&&x.quantity>0);if(d){const distance=dist(citizen.position,d.position),g={type:'GATHER',durationMinutes:12,targetId:d.id,purpose:'self_directed',concepts:[resourceConceptId(d)],payload:{quantity:1}};return {source:'local',concepts:[resourceConceptId(d)],actions:distance>1?[{type:'MOVE',durationMinutes:Math.max(2,Math.ceil(distance*2)),targetId:d.id,targetPosition:d.position,purpose:'self_directed',concepts:[resourceConceptId(d)]},g]:[g]};}}
  if(desired.has('EXPERIMENT')){const held=heldObjects(world,citizen)[0],known=world.resourceDeposits.find(d=>citizen.knownEntityIds.includes(d.id)&&knows(citizen,resourceConceptId(d))),target=held?.id||known?.id;if(target)return {source:'local',concepts,actions:[{type:'EXPERIMENT',durationMinutes:30,targetId:target,purpose:'experiment',concepts,payload:{targetIds:[target],methodCode:'observe'}}]};}
  if(desired.has('COMMUNICATE')||desired.has('TEACH')){const other=world.citizens.find(c=>c.id!==citizen.id&&c.alive&&citizen.knownEntityIds.includes(c.id)&&dist(c.position,citizen.position)<=10),concept=concepts[0];if(other&&concept)return {source:'local',concepts:[concept],actions:[{type:desired.has('TEACH')?'TEACH':'COMMUNICATE',durationMinutes:5,targetId:other.id,purpose:'communicate',concepts:[concept],payload:{concept}}]};}
  const h=hash32(`${world.seed}|${citizen.id}|${Math.floor(at/10)}`),angle=(h%10000)/10000*Math.PI*2,radius=4+((h>>>8)%900)/100,tx=Math.max(5,Math.min(95,citizen.position.x+Math.cos(angle)*radius)),ty=Math.max(5,Math.min(95,citizen.position.y+Math.sin(angle)*radius));
  return {source:'local',concepts,actions:[{type:'MOVE',durationMinutes:Math.max(4,Math.ceil(dist(citizen.position,{x:tx,y:ty})*2)),targetPosition:{x:tx,y:ty},purpose:goal?'self_directed':'explore',concepts:[]},{type:'OBSERVE',durationMinutes:8,purpose:'explore',concepts:[]}]};
}

function safePayload(type,p={}){if(type==='GATHER')return {quantity:Math.max(.1,Math.min(20,Number(p.quantity)||1))};if(['TEACH','COMMUNICATE'].includes(type))return {concept:p.concept?String(p.concept):null,conceptIds:Array.isArray(p.conceptIds)?p.conceptIds.map(String).slice(0,6):[],beliefId:p.beliefId?String(p.beliefId):null,primitiveSignal:['attention','danger','need','point','accept','reject'].includes(p.primitiveSignal)?p.primitiveSignal:null};if(type==='PROMISE')return {kindCode:['join','share','access','exchange','care','defend','other'].includes(p.kindCode)?p.kindCode:'other',purposeConcept:p.purposeConcept?String(p.purposeConcept):null};if(type==='CLAIM')return {predicateCode:['control','use','possession','boundary','authority_over','stewardship','other'].includes(p.predicateCode)?p.predicateCode:'other',subjectId:p.subjectId?String(p.subjectId):null,purposeConcept:p.purposeConcept?String(p.purposeConcept):null};if(type==='EXPERIMENT')return {targetIds:Array.isArray(p.targetIds)?p.targetIds.map(String).slice(0,6):[],methodCode:['observe','compare','stress','heat','combine','measure'].includes(p.methodCode)?p.methodCode:'observe'};if(type==='BUILD')return {projectId:p.projectId?String(p.projectId):null,inputObjectIds:Array.isArray(p.inputObjectIds)?p.inputObjectIds.map(String).slice(0,12):[],site:p.site&&Number.isFinite(Number(p.site.x))&&Number.isFinite(Number(p.site.y))?{x:Number(p.site.x),y:Number(p.site.y)}:null,workMinutes:Math.max(15,Math.min(10000,Number(p.workMinutes)||120)),form:['structure','shelter','platform','enclosure','tower','channel'].includes(p.form)?p.form:'structure'};if(type==='TRANSFER')return {objectId:p.objectId?String(p.objectId):null};if(['ASSEMBLE','CUT','DIG','HEAT','COOL','MIX'].includes(type))return {inputObjectIds:Array.isArray(p.inputObjectIds)?p.inputObjectIds.map(String).slice(0,8):[],quantities:Array.isArray(p.quantities)?p.quantities.map(Number).slice(0,8):[],form:['bundle','flat','elongated','hollow','frame','layered','fragmented'].includes(p.form)?p.form:'bundle'};return {};}
export function sanitizeAIProposal(raw){const p=raw&&typeof raw==='object'?raw:{};return {source:'workers-ai',concepts:Array.isArray(p.concepts)?p.concepts.map(String).slice(0,20):[],beliefUpdates:Array.isArray(p.beliefUpdates)?p.beliefUpdates.slice(0,8).map(b=>({stanceCode:['supports','opposes','uncertain','sacred','taboo','causal','identity','normative'].includes(b.stanceCode)?b.stanceCode:'uncertain',conceptIds:Array.isArray(b.conceptIds)?b.conceptIds.map(String).slice(0,8):[],confidence:Math.max(0,Math.min(1,Number(b.confidence)||.5))})):[],actions:Array.isArray(p.actions)?p.actions.slice(0,8).map(a=>{const type=String(a.type||'').toUpperCase();return {type,durationMinutes:Math.max(1,Math.min(1440,Number(a.durationMinutes)||10)),targetId:a.targetId?String(a.targetId):null,targetPosition:a.targetPosition&&Number.isFinite(Number(a.targetPosition.x))&&Number.isFinite(Number(a.targetPosition.y))?{x:Number(a.targetPosition.x),y:Number(a.targetPosition.y)}:null,purpose:['survival','explore','cooperate','care','experiment','construct','defend','communicate','self_directed'].includes(a.purpose)?a.purpose:'self_directed',concepts:Array.isArray(a.concepts)?a.concepts.map(String).slice(0,12):[],payload:safePayload(type,a.payload)};}):[]};}
export function isSafeReflexProposal(proposal){return proposal.actions.every(a=>SAFE_REFLEX_ACTIONS.has(a.type));}
