import {hash32} from './rng.js';
import {appendEvent} from './ledger.js';
import {knows,learn} from './epistemics.js';
const SYL=['ka','ve','nu','ri','to','sa','mi','lo','pa','ki','za','du','fe','yo','na','wu'];
function ensureLanguage(c){c.language??={primitiveSignals:[],lexicon:{},heard:{},grammarPatterns:{}};c.language.grammarPatterns??={};return c.language;}
export function coinSignal(world,citizen,concept,at=world.clock.worldMinute){if(!knows(citizen,concept))throw new Error(`unknown_concept:${concept}`);const l=ensureLanguage(citizen);if(l.lexicon[concept])return l.lexicon[concept];const h=hash32(`${world.seed}|${citizen.id}|${concept}`);const token=(SYL[h%SYL.length]+SYL[(h>>>4)%SYL.length]).slice(0,8);l.lexicon[concept]=token;appendEvent(world,'SIGNAL_COINED',citizen.id,{token,conceptRef:concept},[],at);return token;}
export function communicate(world,sender,receiver,{concept=null,token=null,concepts=null,tokens=null}={},at=world.clock.worldMinute){if(!sender.alive||!receiver.alive)throw new Error('citizen_dead');const ids=(concepts||[concept]).filter(Boolean).map(String).slice(0,6);if(!ids.length)throw new Error('communication_concept_required');for(const id of ids)if(!knows(sender,id))throw new Error(`unknown_concept:${id}`);const senderLanguage=ensureLanguage(sender),receiverLanguage=ensureLanguage(receiver);const words=(tokens&&tokens.length===ids.length?tokens:ids.map((id,i)=>i===0&&token?token:coinSignal(world,sender,id,at))).map(String);const interpretations=[];for(let i=0;i<ids.length;i++){const id=ids[i],word=words[i];receiverLanguage.heard[word]=(receiverLanguage.heard[word]||0)+1;const prior=Object.entries(receiverLanguage.lexicon).find(([,t])=>t===word)?.[0]||null;let interpretedConcept=prior;if(!prior&&receiverLanguage.heard[word]>=3){receiverLanguage.lexicon[id]=word;learn(receiver,id,{kind:'communication',from:sender.id,token:word,eventId:null},.45,at);interpretedConcept=id;}interpretations.push(interpretedConcept);}
  for(let i=0;i<words.length-1;i++){const pattern=`${words[i]}>${words[i+1]}`;receiverLanguage.grammarPatterns[pattern]=(receiverLanguage.grammarPatterns[pattern]||0)+1;senderLanguage.grammarPatterns[pattern]=(senderLanguage.grammarPatterns[pattern]||0)+1;}
  appendEvent(world,'COMMUNICATION',sender.id,{receiverId:receiver.id,tokens:words,senderConcepts:ids,receiverInterpretations:interpretations},[],at);return {senderConcept:ids.length===1?ids[0]:null,senderConcepts:ids,receiverInterpretations:interpretations,tokens:words};}
