import {appendEvent} from './ledger.js';
import {stableId} from './rng.js';

// Phenomenological material properties: these are world physics, not social knowledge.
// Citizens still need in-world experiments/teaching to gain actionable knowledge about them.
export const MATERIAL_PROPERTIES=Object.freeze({
  water:{density:1,friction:.02,hardness:0,toughness:0,structuralIntegrity:0,combustible:false,nutrition:0,thermalResistance:.05,waterResistance:0,precipitationResistance:0},
  food:{density:.7,friction:.35,hardness:.04,toughness:.08,structuralIntegrity:12,combustible:true,nutrition:1,thermalResistance:.12,waterResistance:.08,precipitationResistance:.08},
  timber:{density:.6,friction:.48,hardness:.3,toughness:.58,structuralIntegrity:105,combustible:true,thermalResistance:.55,waterResistance:.38,precipitationResistance:.38},
  stone:{density:2.5,friction:.78,hardness:.8,toughness:.62,structuralIntegrity:430,compressiveStrength:900,combustible:false,thermalResistance:.28,waterResistance:.92,precipitationResistance:.92},
  clay:{density:1.6,friction:.62,hardness:.25,toughness:.38,structuralIntegrity:135,compressiveStrength:280,combustible:false,thermalResistance:.48,waterResistance:.8,precipitationResistance:.8},
  ore:{density:3.4,friction:.66,hardness:.7,toughness:.7,structuralIntegrity:520,compressiveStrength:760,combustible:false,thermalResistance:.14,waterResistance:.94,precipitationResistance:.94},
  fiber:{density:.35,friction:.5,hardness:.1,toughness:.32,structuralIntegrity:55,combustible:true,thermalResistance:.67,waterResistance:.58,precipitationResistance:.58},
  biomass:{density:1.02,friction:.45,hardness:.08,toughness:.2,structuralIntegrity:28,combustible:true,nutrition:.1,thermalResistance:.34,waterResistance:.18,precipitationResistance:.18},
  composite:{density:1,friction:.55,hardness:.4,toughness:.45,structuralIntegrity:180,combustible:false,thermalResistance:.5,waterResistance:.68,precipitationResistance:.68}
});
export function objectMass(o){return Math.max(0,Number(o.quantity)||0)*Math.max(0,Number(o.massPerUnitKg)||1);}
export function totalTrackedMass(world){
  const objectKg=world.objects.reduce((s,o)=>s+objectMass(o),0),depositKg=world.resourceDeposits.reduce((s,d)=>s+Math.max(0,Number(d.quantity)||0),0),reserveKg=Math.max(0,Number(world.reserves?.observerEmbodimentKg)||0),citizenKg=world.citizens.filter(c=>c.alive).reduce((s,c)=>s+Math.max(0,Number(c.body?.massKg)||0),0),buildingKg=(world.buildings||[]).reduce((s,b)=>s+Math.max(0,Number(b.massKg)||0),0),naturalKg=Object.values(world.environment?.naturalReservoirs||{}).reduce((s,v)=>s+Math.max(0,Number(v)||0),0),metabolicKg=Math.max(0,Number(world.environment?.metabolicMatterKg)||0);
  return objectKg+depositKg+reserveKg+citizenKg+buildingKg+naturalKg+metabolicKg;
}
export function transferObject(world,objectId,toHolderId,at=world.clock.worldMinute){const o=world.objects.find(x=>x.id===objectId);if(!o)throw new Error('object_not_found');const from=o.holderId;o.holderId=toHolderId;appendEvent(world,'OBJECT_TRANSFERRED',from,{objectId,toHolderId},[],at);return o;}
export function consumeObjectQuantity(world,objectId,quantity,causeId=null,at=world.clock.worldMinute){const o=world.objects.find(x=>x.id===objectId);if(!o)throw new Error('object_not_found');const q=Math.max(0,Number(quantity));if(o.quantity<q)throw new Error('insufficient_material');o.quantity-=q;appendEvent(world,'MATERIAL_CONSUMED','world',{objectId,quantity:q},causeId?[causeId]:[],at);return q;}
export function transformMaterials(world,citizen,spec,at=world.clock.worldMinute){let consumedMass=0;for(const item of spec.consume||[]){const o=world.objects.find(x=>x.id===item.objectId);if(!o||o.holderId!==citizen.id)throw new Error('transformation_input_unavailable');consumedMass+=Math.max(0,Number(item.quantity))*Math.max(0,Number(o.massPerUnitKg)||1);}const outMass=Math.max(0,Number(spec.output.quantity))*Math.max(0,Number(spec.output.massPerUnitKg)||1);if(Math.abs(consumedMass-outMass)>.000001)throw new Error('mass_not_conserved');const cause=appendEvent(world,'TRANSFORMATION_STARTED',citizen.id,{process:spec.process||'generic',inputObjectIds:(spec.consume||[]).map(x=>x.objectId)},[],at);for(const item of spec.consume||[])consumeObjectQuantity(world,item.objectId,item.quantity,cause.id,at);const inputs=(spec.consume||[]).map(item=>world.objects.find(x=>x.id===item.objectId)).filter(Boolean);const numericKeys=new Set(inputs.flatMap(o=>Object.keys(o.properties||MATERIAL_PROPERTIES[o.material]||{}).filter(k=>typeof (o.properties||MATERIAL_PROPERTIES[o.material]||{})[k]==='number')));const properties={};for(const k of numericKeys){const vals=inputs.map(o=>(o.properties||MATERIAL_PROPERTIES[o.material]||{})[k]).filter(v=>typeof v==='number');if(vals.length)properties[k]=vals.reduce((a,b)=>a+b,0)/vals.length;}const o={id:stableId('obj',citizen.id,world.objects.length,at,spec.process),kind:spec.output.kind||'artifact',material:spec.output.material||'composite',quantity:Number(spec.output.quantity),massPerUnitKg:Number(spec.output.massPerUnitKg)||1,properties,holderId:citizen.id,position:{...citizen.position},condition:1,provenance:{type:'TRANSFORMATION',process:spec.process||'generic',eventId:cause.id,inputObjectIds:(spec.consume||[]).map(x=>x.objectId)}};world.objects.push(o);citizen.possessions??=[];if(!citizen.possessions.includes(o.id))citizen.possessions.push(o.id);citizen.knownEntityIds??=[citizen.id];if(!citizen.knownEntityIds.includes(o.id))citizen.knownEntityIds.push(o.id);appendEvent(world,'TRANSFORMATION_COMPLETED',citizen.id,{objectId:o.id,process:spec.process||'generic',massKg:outMass},[cause.id],at);return o;}
export function advanceDecomposition(world,deltaMinutes,at=world.clock.worldMinute){const e=world.environment;e.naturalReservoirs??={waterKg:0,biomassKg:0,mineralKg:0};for(const o of world.objects){if(o.provenance?.type!=='CORPSE'||o.quantity<=0)continue;const fraction=Math.min(.02,Math.max(0,deltaMinutes)/525600*.9),q=o.quantity*fraction;if(q<=0)continue;o.quantity-=q;e.naturalReservoirs.biomassKg=(e.naturalReservoirs.biomassKg||0)+q*o.massPerUnitKg;o.condition=Math.max(0,o.condition-fraction);appendEvent(world,'DECOMPOSITION','world',{objectId:o.id,massKg:q*o.massPerUnitKg},[],at);}}
