import {stableId,hash32} from './rng.js';
import {recombineGenomes} from './genetics.js';
import {PRIMITIVE_SIGNALS} from './constants.js';
import {appendEvent} from './ledger.js';
import {ensureCognitionState} from './cognition-state.js';

const GESTATION_MINUTES=280*1440;
function adult(c){return c.body.ageMinutes>=16*525600;}
export function conceive(world,a,b,at=world.clock.worldMinute){if(!a?.alive||!b?.alive)throw new Error('parent_unavailable');const gestating=a.body.reproductiveRole==='gestating'?a:b.body.reproductiveRole==='gestating'?b:null;const partner=gestating===a?b:a;if(!gestating||partner.body.reproductiveRole!=='non_gestating')throw new Error('reproductive_roles_incompatible');if(!adult(gestating)||!adult(partner))throw new Error('biological_maturity_required');if(gestating.body.pregnancy)throw new Error('pregnancy_already_active');const p={id:stableId('pregnancy',gestating.id,partner.id,at),partnerId:partner.id,conceivedWorldMinute:at,dueWorldMinute:at+GESTATION_MINUTES};gestating.body.pregnancy=p;appendEvent(world,'CONCEPTION',gestating.id,{pregnancyId:p.id,partnerId:partner.id,dueWorldMinute:p.dueWorldMinute},[],at);return p;}
function newborn(world,mother,partner,at,pregnancy){const genome=recombineGenomes(mother.genome,partner.genome,pregnancy.id);const id=stableId('citizen',pregnancy.id,'birth');const role=hash32(id)%2?'gestating':'non_gestating';const c={id,kind:'BORN_IN_WORLD',selfName:null,externalId:null,alive:true,birthWorldMinute:at,deathWorldMinute:null,position:{...mother.position},genome,body:{massKg:3.2+(hash32(id)%700)/1000,hydration:96,calories:96,sleepPressure:15,temperatureC:36.8,health:100,injuries:[],diseases:[],fertility:genome.fertility,pregnancy:null,reproductiveRole:role,ageMinutes:0,alive:true},psychology:{curiosity:.45, riskTolerance:.25,socialDrive:.8,aggression:.08,empathy:.55,noveltySeeking:.5,stress:.2,fear:.15,attachment:.75,confidence:.1},knowledge:[],memories:[],knownEntityIds:[id,mother.id,partner.id],skills:{},language:{primitiveSignals:[...PRIMITIVE_SIGNALS],lexicon:{},heard:{},grammarPatterns:{}},beliefs:[],relationships:{[mother.id]:{familiarity:.8,trust:.5,affection:.6,fear:0,obligation:0},[partner.id]:{familiarity:.3,trust:.2,affection:.25,fear:0,obligation:0}},possessions:[],goals:[],activeGoal:null,plans:[],currentActionId:null,commitments:[],cognition:{lastReflectionMinute:null,pending:true,reason:'birth'}};ensureCognitionState(c,at);return c;}
export function advancePregnancies(world,toMinute){const born=[];for(const mother of [...world.citizens]){const p=mother.body.pregnancy;if(!p||p.dueWorldMinute>toMinute||!mother.alive)continue;const partner=world.citizens.find(c=>c.id===p.partnerId);if(!partner){mother.body.pregnancy=null;continue;}const child=newborn(world,mother,partner,p.dueWorldMinute,p);if(mother.body.massKg<=child.body.massKg+35){mother.body.pregnancy=null;appendEvent(world,'PREGNANCY_LOSS',mother.id,{pregnancyId:p.id,reason:'insufficient_biological_mass'},[p.id],p.dueWorldMinute);continue;}mother.body.massKg-=child.body.massKg;world.citizens.push(child);mother.body.pregnancy=null;world.cognitionQueue.push({citizenId:child.id,reason:'birth',priority:.9});appendEvent(world,'BIRTH',child.id,{motherId:mother.id,partnerId:partner.id,pregnancyId:p.id},[p.id],p.dueWorldMinute);born.push(child);}return born;}
