import { DEFAULT_STRATEGY } from "./cymscript.js";
const EVENT_SINK=Symbol("eventSink");
const DISTRICTS=["central","research","commerce","industry","residential","logistics","civic","harbor"];
const SECTORS=["technology","research","mobility","housing","food","energy","security","logistics","finance","media"];
const NAMES=["AURA","KAIROS","NEXUS","ORION","LYRA","ATLAS","NOVA","SABLE","HELIOS","MIRA","VANTA","CYRA","LUMEN","AXIS","SOL","VEGA"];
function hash(s){let h=2166136261>>>0; for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)} return h>>>0}
function rnd(seed){let x=hash(seed)||1; return ()=>((x=(Math.imul(x^x>>>15,1|x)+(x^x>>>7))^x)>>>0)/4294967296}
function id(prefix,n){return `${prefix}:${String(n).padStart(4,"0")}`}
function event(world,type,actor_id,payload={},causes=[]){const legacySequence=()=>world.events.reduce((max,e)=>{const n=Number(String(e?.id||"").split(":")[2]);return Number.isFinite(n)?Math.max(max,n):max},-1)+1;const sequence=world.event_sequence??legacySequence();world.event_sequence=sequence+1;const e={id:`evt:${world.tick}:${sequence}:${hash(JSON.stringify(payload))}`,tick:world.tick,type,actor_id,payload,causes,ts:world.started_at};world.events.push(e);world[EVENT_SINK]?.(e); if(world.events.length>5000) world.events.splice(0,world.events.length-5000); return e;}
function pos(i){const ring=Math.floor(i/18); const a=(i%18)/18*Math.PI*2; return {x:50+Math.cos(a)*(16+ring*6),y:50+Math.sin(a)*(11+ring*4)} }
export function createWorld({seed=20260914,started_at="2026-09-14T00:00:00.000Z"}={}){const r=rnd(seed); const citizens=[]; for(let i=1;i<=100;i++){const p=pos(i-1); citizens.push({id:id("founder",i),name:`${NAMES[(i-1)%NAMES.length]}-${String(i).padStart(3,"0")}`,kind:"GENESIS_FOUNDER",github_id:null,balance:500+Math.floor(r()*1000),reputation:10,energy:70+Math.floor(r()*30),sector:SECTORS[i%SECTORS.length],district:DISTRICTS[i%DISTRICTS.length],x:p.x,y:p.y,target_x:p.x,target_y:p.y,status:"exploring",company_id:null,strategy:{...DEFAULT_STRATEGY,risk:["low","medium","high"][i%3],company_threshold:1100+((i*37)%900),prefer:[SECTORS[i%SECTORS.length]]}})}
 const world={schema:1,seed,tick:0,started_at,citizens,companies:[],buildings:[],jobs:[],needs:[],innovations:[],events:[],institutions:{central_bank:{policy_rate:2.5,inflation:2.2,money_supply:citizens.reduce((a,c)=>a+c.balance,0),status:"stable"},government:{treasury:5000,tax_rate:.08},justice:{open_cases:0},police:{active:8}},metrics:{population:100,companies:0,buildings:0,unemployment:1,crime_rate:0},agent_status:"fallback"}; event(world,"WORLD_GENESIS","system",{founders:100,seed}); return world;}
function transfer(world,from,to,amount,kind,meta={}){amount=Math.max(0,Math.floor(amount*100)/100); if(!amount||from.balance<amount)return false;from.balance-=amount;to.balance+=amount; event(world,kind,from.id,{to:to.id,amount,...meta});return true}
function discoverNeed(world){if(world.tick%6!==0)return; const types=["mobility","housing","goods","security","energy","information"]; const type=types[(world.tick/6+world.seed)%types.length|0]; if(world.needs.some(n=>n.type===type&&n.status==="open"))return; const n={id:`need:${world.tick}:${type}`,type,severity:.45+((hash(type+world.tick)%45)/100),status:"open",created_tick:world.tick,district:DISTRICTS[hash(type)%DISTRICTS.length],evidence:`Observed ${type} pressure at tick ${world.tick}`};world.needs.push(n); event(world,"NEED_DISCOVERED","observatory",n);}
function innovate(world){const n=world.needs.find(x=>x.status==="open"&&world.tick-x.created_tick>=1); if(!n)return; const founder=world.citizens.filter(c=>!c.company_id).sort((a,b)=>b.balance-a.balance)[0]; if(!founder||founder.balance<300)return; const innovation={id:`innovation:${n.type}:${world.tick}`,name:`${n.type[0].toUpperCase()+n.type.slice(1)} ${["Exchange","Works","Network","Lab"][hash(n.id)%4]}`,need_id:n.id,sector:n.type,inputs:["capital","labor"],output:`${n.type}_service`,owner_id:null,created_tick:world.tick,version:1};world.innovations.push(innovation);const company=foundCompany(world,founder,n.type,innovation);if(company){innovation.owner_id=company.id;n.status="addressed";event(world,"INNOVATION_CREATED",founder.id,innovation,[n.id]);}}
function foundCompany(world,citizen,sector,innovation=null){const capital=Math.min(Math.max(250,Math.floor(citizen.balance*.35)),750); if(citizen.balance<capital)return null; citizen.balance-=capital; const c={id:`company:${world.companies.length+1}`,name:`${citizen.name.split("-")[0]} ${sector[0].toUpperCase()+sector.slice(1)}`,founder_id:citizen.id,sector,treasury:capital,revenue:0,employees:[],building_id:null,status:"forming",innovation_id:innovation?.id||null,district:DISTRICTS[hash(sector+citizen.id)%DISTRICTS.length],x:25+(hash(citizen.id)%50),y:25+(hash(sector+citizen.id)%50)};world.companies.push(c);citizen.company_id=c.id;event(world,"COMPANY_FOUNDED",citizen.id,{company_id:c.id,sector,capital}); startConstruction(world,c);return c;}
function startConstruction(world,company){const b={id:`building:${world.buildings.length+1}`,company_id:company.id,type:company.sector==="housing"?"residence":company.sector==="research"?"research_hub":"company_hq",district:company.district,x:company.x,y:company.y,stage:"survey",progress:0,status:"construction"};world.buildings.push(b);company.building_id=b.id;event(world,"CONSTRUCTION_STARTED",company.id,{building_id:b.id,type:b.type});}
function progressConstruction(world){for(const b of world.buildings.filter(b=>b.status==="construction")){b.progress=Math.min(100,b.progress+12+(hash(b.id+world.tick)%10)); const stages=["survey","foundation","frame","envelope","fit_out","operational"]; b.stage=stages[Math.min(stages.length-1,Math.floor(b.progress/20))]; if(b.progress>=100){b.status="operational";b.stage="operational"; const c=world.companies.find(c=>c.id===b.company_id);if(c)c.status="operational";event(world,"BUILDING_COMPLETED",b.company_id,{building_id:b.id});}}}
function work(world){const operational=world.companies.filter(c=>c.status==="operational");if(!operational.length)return; for(const citizen of world.citizens){const company=operational[hash(citizen.id+world.tick)%operational.length]; if(!company)continue; if(!company.employees.includes(citizen.id)&&company.employees.length<8){company.employees.push(citizen.id);citizen.company_id=citizen.company_id||company.id;event(world,"JOB_ACCEPTED",citizen.id,{company_id:company.id});} if(company.employees.includes(citizen.id)){const salary=4+(hash(citizen.id+world.tick)%5);if(company.treasury>=salary){company.treasury-=salary;const tax=salary*world.institutions.government.tax_rate;citizen.balance+=salary-tax;world.institutions.government.treasury+=tax;company.revenue+=Math.round((salary*1.35)*100)/100;company.treasury+=salary*1.35;citizen.status="working";citizen.target_x=company.x;citizen.target_y=company.y;if(world.tick%4===0)event(world,"WORK_SHIFT",citizen.id,{company_id:company.id,salary,tax});}}}}
function consume(world){const sellers=world.companies.filter(c=>c.status==="operational"); if(!sellers.length)return; for(const citizen of world.citizens.filter((_,i)=>i%5===world.tick%5)){const company=sellers[hash(citizen.id+"buy"+world.tick)%sellers.length];const price=3+(hash(company.id+world.tick)%7);if(citizen.balance>price+citizen.strategy.min_liquidity*.05){citizen.balance-=price;company.treasury+=price;company.revenue+=price;event(world,"MARKET_PURCHASE",citizen.id,{company_id:company.id,amount:price,innovation_id:company.innovation_id});}}}
function crimeAndJustice(world){for(const c of world.citizens.filter(c=>c.strategy.crime)){if(hash(c.id+world.tick)%31===0){const gain=10+(hash(c.id)%25);c.balance+=gain;event(world,"CRIME_RECORDED",c.id,{kind:"economic_fraud_simulated",gain}); if(hash("police"+c.id+world.tick)%100<65){world.institutions.justice.open_cases++;event(world,"INVESTIGATION_OPENED","police",{citizen_id:c.id}); if(hash("case"+c.id+world.tick)%100<70){const fine=Math.min(c.balance,Math.round(gain*1.5));c.balance-=fine;world.institutions.government.treasury+=fine;c.reputation=Math.max(0,c.reputation-5);event(world,"JUSTICE_SENTENCE","justice",{citizen_id:c.id,fine,custody_ticks:hash(c.id)%4});}}}}}
function institutions(world){const bank=world.institutions.central_bank;const spend=world.events.slice(-200).filter(e=>e.type==="MARKET_PURCHASE").reduce((s,e)=>s+Number(e.payload.amount||0),0);bank.inflation=Math.round((1.5+Math.min(8,spend/250))*100)/100;if(world.tick%8===0){const old=bank.policy_rate; if(bank.inflation>4)bank.policy_rate=Math.min(9,bank.policy_rate+.25);else if(bank.inflation<2)bank.policy_rate=Math.max(0,bank.policy_rate-.25); if(old!==bank.policy_rate)event(world,"CENTRAL_BANK_POLICY","central_bank",{from:old,to:bank.policy_rate,inflation:bank.inflation});}}
function autonomousFounding(world){for(const c of world.citizens.filter(c=>!c.company_id)){if(c.balance>=c.strategy.company_threshold && hash(c.id+world.tick)%17===0){foundCompany(world,c,c.strategy.prefer?.[0]||c.sector);break;}}}
function move(world){for(const c of world.citizens){c.x+=(c.target_x-c.x)*.18;c.y+=(c.target_y-c.y)*.18;if(Math.abs(c.target_x-c.x)<.2){const p=pos(hash(c.id+world.tick)%100);c.target_x=p.x;c.target_y=p.y;}}}
function metrics(world){const employed=new Set(world.companies.flatMap(c=>c.employees));world.metrics={population:world.citizens.length,companies:world.companies.length,buildings:world.buildings.length,unemployment:Math.round((1-employed.size/world.citizens.length)*1000)/1000,crime_rate:Math.round(world.events.slice(-200).filter(e=>e.type==="CRIME_RECORDED").length/Math.max(1,world.citizens.length)*1000)/1000};world.institutions.central_bank.money_supply=Math.round((world.citizens.reduce((s,c)=>s+c.balance,0)+world.companies.reduce((s,c)=>s+c.treasury,0)+world.institutions.government.treasury)*100)/100}
export function addHumanCitizen(world,{github_id,login,display_name=null}){let c=world.citizens.find(c=>String(c.github_id)===String(github_id));if(c)return c; const p=pos(world.citizens.length);c={id:`human:${github_id}`,name:display_name||login,login,kind:"HUMAN_LINKED",github_id:Number(github_id),balance:500,reputation:0,energy:100,sector:"technology",district:"residential",x:p.x,y:p.y,target_x:p.x,target_y:p.y,status:"arrived",company_id:null,strategy:{...DEFAULT_STRATEGY,prefer:[...DEFAULT_STRATEGY.prefer]}};world.citizens.push(c);event(world,"HUMAN_CITIZEN_ARRIVED",c.id,{github_id:Number(github_id),login});metrics(world);return c}
export function applyCitizenStrategy(world,citizenId,strategy){const c=world.citizens.find(c=>c.id===citizenId);if(!c)throw new Error("citizen_not_found");c.strategy={...DEFAULT_STRATEGY,...strategy,prefer:[...(strategy.prefer||DEFAULT_STRATEGY.prefer)]};event(world,"STRATEGY_ACTIVATED",c.id,{goal:c.strategy.goal,risk:c.strategy.risk,mode:c.strategy.mode});return c.strategy}
export function tickWorld(world){world.tick++;discoverNeed(world);innovate(world);autonomousFounding(world);progressConstruction(world);work(world);consume(world);crimeAndJustice(world);institutions(world);move(world);metrics(world);return world}
export function advanceWorld(world,ticks=1,onEvent){const previousSink=world[EVENT_SINK];world[EVENT_SINK]=onEvent;try{for(let i=0;i<Math.max(0,Math.min(10000,Number(ticks)||0));i++)tickWorld(world);return world}finally{if(previousSink)world[EVENT_SINK]=previousSink;else delete world[EVENT_SINK]}}
export function publicWorld(world){return {schema:world.schema,tick:world.tick,seed:world.seed,started_at:world.started_at,citizens:world.citizens.map(({strategy,...c})=>c),companies:world.companies,buildings:world.buildings,needs:world.needs,innovations:world.innovations,events:world.events.slice(-250),institutions:world.institutions,metrics:world.metrics,agent_status:world.agent_status}}
export function explainEvent(world,eventId,depth=4){const by=new Map(world.events.map(e=>[e.id,e]));const root=by.get(eventId);if(!root)return null;const walk=(e,d)=>({event:e,causes:d>0?(e.causes||[]).map(id=>by.get(id)).filter(Boolean).map(x=>walk(x,d-1)):[]});return walk(root,depth)}
