import {readFileSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
const root=resolve(process.argv[2]||'.'),file=resolve(root,'world/engine.js');
let s=readFileSync(file,'utf8');
function once(from,to,label){const count=s.split(from).length-1;if(count===0){if(s.includes(to))return;throw new Error(`engine patch anchor missing: ${label}`);}if(count!==1)throw new Error(`engine patch anchor ambiguous (${count}): ${label}`);s=s.replace(from,to);}
once("body:{hydration:c.body.hydration,calories:c.body.calories,sleepPressure:c.body.sleepPressure,health:c.body.health,ageMinutes:c.body.ageMinutes,diseases:c.body.diseases.length,injuries:c.body.injuries.length}","body:{hydration:c.body.hydration,calories:c.body.calories,sleepPressure:c.body.sleepPressure,health:c.body.health,ageMinutes:c.body.ageMinutes,temperatureC:c.body.temperatureC,exposure:c.body.exposure||null,reproductiveRole:c.body.reproductiveRole||null,pregnancy:c.body.pregnancy?{dueWorldMinute:c.body.pregnancy.dueWorldMinute}:null,diseases:c.body.diseases.length,injuries:c.body.injuries.length}",'public body physics');
once("targetId:action.targetId}:null","targetId:action.targetId,path:action.path||null,physics:action.physics||null}:null",'public action route physics');
once("objects:world.objects.filter(o=>o.quantity>0).map(o=>({id:o.id,kind:o.kind,quantity:o.quantity,holderId:o.holderId,position:o.position,condition:o.condition,provenance:o.provenance}))","objects:world.objects.filter(o=>o.quantity>0).map(o=>({id:o.id,kind:o.kind,material:o.material||null,quantity:o.quantity,massPerUnitKg:o.massPerUnitKg,holderId:o.holderId,position:o.position,condition:o.condition,properties:o.properties||null,provenance:o.provenance}))",'public object material');
once("for(const a of completed){resolveAction(world,a,a.endsWorldMinute);const c=world.citizens.find(x=>x.id===a.actorId);if(c?.alive&&!continuePlan(world,c,a,a.endsWorldMinute))queueCognition(world,c,'plan_completed',.42);}","for(const a of completed){let resolved=true;try{resolveAction(world,a,a.endsWorldMinute);}catch(error){resolved=false;const reason=String(error?.message||error).slice(0,160),ev=appendEvent(world,'ACTION_RESOLUTION_FAILED',a.actorId,{actionId:a.id,type:a.type,reason},[a.id],a.endsWorldMinute),c=world.citizens.find(x=>x.id===a.actorId);if(c?.alive){const plan=a.planId?c.plans.find(p=>p.id===a.planId):null;if(plan)plan.status='failed';recordMemory(c,{kind:'episodic',content:{actionFailure:{actionId:a.id,type:a.type,reason}},source:{kind:'physical_outcome',eventId:ev.id},confidence:1,salience:.75,worldMinute:a.endsWorldMinute});queueCognition(world,c,'physical_action_failed',.85);}}const c=world.citizens.find(x=>x.id===a.actorId);if(resolved&&c?.alive&&!continuePlan(world,c,a,a.endsWorldMinute))queueCognition(world,c,'plan_completed',.42);}",'physical action failure is canonical, not fatal');
if(!s.includes('recentLedger:world.ledger.slice(-80)'))once("ledgerHead:world.ledgerHead};","recentLedger:world.ledger.slice(-80).filter(e=>['PHYSICAL_IMPACT','STRUCTURE_DAMAGED','STRUCTURE_FRACTURED'].includes(e.type)).map(e=>({id:e.id,type:e.type,worldMinute:e.worldMinute,actorId:e.actorId,payload:e.payload,causes:e.causes})),ledgerHead:world.ledgerHead};",'public recent physical events');
writeFileSync(file,s);
console.log('Patched public Sovereign World projection for physical routes, exposure and material visibility.');
